### ISSUE TITLE
Equity compensation discussion

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/the-salary-question#1]
Found these articles particularly helpful in understanding non-cash comp. Perhaps they could be included to help students with all comp discussions:

http://rob.by/2013/negotiating-your-startup-job-offer/
http://venturehacks.com/articles/option-pool-shuffle#market
http://www.inc.com/atish-davda/5-questions-you-should-ask-before-taking-a-start-up-job-offer.html

**Comment by AnnJohn** [comment]
thanks @onyoo! will add this to a list of resources in the lesson
